language: java
script: "src/compileFiles.bat"
jdk:
  - openjdk7
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ra5DVV59K+wcj2H4P+VHA/YZEI4XaJukCYTRr53Eni8Op4ALxZ0IzaldZrNVNsJ2kAs6U+drgK5Ml/ptL2lDaXyz+sEYvOVih6HF7RQFEL6Lb/t80lre7dXxB8T8qhUicGMEUEMvjkntGzQw9kicID9K+MFud+1kxZrLhhWPaouGOl8UVCaWt4/M3iDCyPIM0MHN3r8R8AavYuQlfWT3kVOjSlXSQ6CiwYen37KlUpNJNcuGGmd6KnYtLez/ZWCZzUQN70axb4Dm43Hkay4qgFNcQiJKYXvDOdORCSJlymrvwaGRHtF3wwletOBOvEvO9XnW9R+uWEowRtcgGhNWV/q5juaS/nLj1fe2n3g3YEf+SRfhUUa3KJZlUDd2Swpe4A0jE6ZWpaGK1Yj9vPV8rkHlzWr28O0p9JCdC9gpWpxySlwO91GlYE8ND9aRFxj4aD45E7uy6PDreWfAK9o7V2bT7ukK/CjbGtmR2jZDS0mew7MiStbj86Hi1UBJTbN4m8CLVJ8ZluvOsa9WyHkS4IKfkh+9D+J3y4dBtVVKyCISTQ7aVIGAY+bSUCe8DjveXcsdxo+7PAUsZVDNy2ikctXWKPbcRKfE/VU5WBQgW0T2VHbDdprrWmfhgDt9FsWuLxUlHEU/hXUv7ww3ti7EhFlmJ3NEqHyo5oQ7VIFb6NQ="

addons:
  coverity_scan:
    project:
      name: "Lanhbao/Juliet"
      description: "Build submitted via Travis CI"
    notification_email: anhtluet12@gmail.com
    build_command_prepend:
    build_command:   "src/compileFiles.bat"
    branch_pattern: coverity_scan
